/**
 * Patient reviews, as published on the practice's Google Business Profiles for
 * the Fremont and Hayward clinics and captured on 16 and 17 September 2026.
 * Every quote is verbatim — spelling, line breaks and signatures included —
 * because these are patients' own words, not copy.
 *
 * One-star reviews are left out of this file at the practice's direction, so
 * RATING_TOTAL and RATING_SUM describe the 86 reviews kept here rather than
 * everything the two profiles carry. The two listings share no reviewer between
 * them, so nothing is counted twice.
 */

export type Review = {
  /** The reviewer's Google display name, as they wrote it. */
  name: string
  /** Their Google contributor line, e.g. 'Local Guide·16 reviews·8 photos'. */
  meta: string
  /** The clinic the review was left for. */
  location: string
  /** Google's own relative date, as it read on the day of capture. Kept for the record; the card shows the clinic instead. */
  date: string
  rating: number
  body: string
}

/** Every review kept in this file. */
export const RATING_TOTAL = 86

/**
 * The rating the practice publishes. It is stated rather than worked out from
 * the reviews below, which average 4.97 once the one-star ones are taken out --
 * a number that would read as though nobody had ever been dissatisfied. 4.8 is
 * the figure the practice stands behind and it sits under what this file would
 * compute, so the site never claims more than its own reviews support.
 */
export const RATING_AVERAGE = '4.8'

export const GOOGLE_REVIEWS_URL = 'https://www.google.com/search?q=Mission+Primary+Care+Fremont+reviews'

export const reviews: Review[] = [
  { name: 'AC Sto', meta: '7 reviews', location: 'Fremont', date: '4 years ago', rating: 5, body: 'Dr. Bhandari❤\n\nMy husband and I have been patients of of Dr. Bhandari at MPC for 20 years.\nOur children,  our hospice bound family members ALL have been fortunate enough to have this fine group of doctors to care for them.\n\nAlthough we have moved out of the Bay Area.\nFor the last 7 years. ANY TIME we have had an emergency we\'ve gladly traveled 6 plus hours one way just to be treated by this wonderful man.\n\nGoing back recently to be treated again.\nIt\'s always like a visit with a family member who really truly cares.\n\nAlthough we have medical insurance in our county.\nIt doesn\'t cover this doctors area. We are more than happy to give cash at any time just to get a professional recommendation by them.\nThey\'re just THAT GOOD.\n\nWe HIGHLY RECOMMEND this group of splendid Gentlemen.\nDr. Pareek❤\nDr. Chan❤\nAnd of course our Dr. Bhandari❤❤ we appreciate you all so so much!\nThank you!' },
  { name: 'Anne', meta: 'Local Guide·16 reviews·8 photos', location: 'Fremont', date: '3 years ago', rating: 5, body: 'Dr.Bhandari and his staff at Mission Primary Care are very professional, helpful and kind. I needed urgent assistance with a procedure, and they made it happen. They jumped through hoops with the insurance company and got me scheduled right away. I missed an appointment due to a scheduling conflict with my primary care,  and they were very understanding and kind.\nIn today\'s world of red tape and insurance nightmares,  I thought there was no hope of getting the procedure done quickly, but they were so helpful and patient with all my questions.\n\nI first saw Dr Bhandari in the hospital.  He came in and answered all of my questions, and assured me that his office would help me with all the follow-up that I needed.\n\nI appreciate all the staff at Mission Primary Care.' },
  { name: 'Deen Maqdoor', meta: '1 review', location: 'Fremont', date: '6 years ago', rating: 5, body: 'I have the utmost respect for Dr. Bhupinder  Bahndari.  Excellent medical (and other) advices. The front office runs just as competently as he does, by Dana, Shokria, and Carla.  The place is organized and friendly.\n\nStaff is very responsive to emails for appointments, Rx refills and general medical questions.  I am also impressed by other providers/services they\'ve referred me to.\n\nBelal Maqdoor' },
  { name: 'Subramanian Balakrishnan', meta: '3 reviews', location: 'Hayward', date: '6 years ago', rating: 5, body: 'All calls are attended without fail.Inspite doctor\'s busy schedule appointments are given as per my request.Appointment is pre-confirmed and doctor calls very promptly and talks very pleasantly without any inhibitions and prescribes apt medicines and notify to the nearest pharmacy Everything is done professionally from top to bottom' },
  { name: 'Rachel Espino', meta: '1 review', location: 'Hayward', date: '6 years ago', rating: 5, body: 'Hi! Today for the first time I had my appointment with my Doctor by Curogram.com  and it was great I was very please the way How we can see each other and  how we Conversate! I recommend this way to meat with your Doctor especially the way the situation is right now I was very pleased thank you Mission Primary Clinic!!!' },
  { name: 'Mitra Karagah', meta: '1 review', location: 'Hayward', date: '6 years ago', rating: 5, body: 'This was the second time I had a video call visit and it was very convenient.The staff was very friendly and helpful with getting me an appointment right away.\nDr Niala Saeed was as caring and wonderful as always and listen to all my concerns.Over all I was very happy with the entire experience.' },
  { name: 'Elaine Leonard', meta: 'Local Guide · 47 reviews · 2 photos', location: 'Hayward', date: '6 years ago', rating: 5, body: 'Today was the first time I used the video appointment and it was easy to use and affective, the quality was great and my doctor why does Awesome. Mary is always professional but today she over-extending herself to assist me on using video appointment for the first time. Thank you so much 😊 …' },
  { name: 'Peggy Martinez', meta: '5 reviews', location: 'Hayward', date: '6 years ago', rating: 5, body: 'Mission Clinic provides good quality care. Its staff thoroughly communicated with me even during this difficult stretch of time under Covid-19. The staff helped me through several processes, including viewing and uploading my data through the Curogram app. I highly recommend Mission Clinic.' },
  { name: 'Monica Martinez', meta: '1 review', location: 'Hayward', date: '5 years ago', rating: 5, body: 'Hello, I want to thank the staff and practisionar for a wonderful experience at their facility. I felt welcomed by the staff and enjoyed my visit with them. I recommend this office to others who are looking for caring staff and doctors.\n\nMonica Rivera' },
  { name: 'Carole Wang', meta: '5 reviews', location: 'Hayward', date: '6 years ago', rating: 5, body: 'They are so professional, they made sure to take your temperature and ask all the questions before you step into the office. I was amazed at the waiting area with 5 chairs all 6 feet apt, all the staffs are friendly and clear, I love the Doctors there.' },
  { name: 'tiryaD nylsaE', meta: '1 review', location: 'Fremont', date: '5 years ago', rating: 5, body: 'This clinic gets a 15 out of 10 in my book, very comfortable vibe, the lady at the front desk made the experience feel like I was family and not another number attached to a file.\n\nAs well as the doctor, very professional and genuine sense of care.' },
  { name: 'bobby daljit', meta: '5 reviews', location: 'Hayward', date: '6 years ago', rating: 5, body: 'I had a great experience with Mission Primary Care. The doctor was very nice and friendly with me. She explained things very nicely to me and showed she really cared for me. She also spoke to me in my language. I will surely refer them to everyone.' },
  { name: 'MsAnn Johnson', meta: 'Local Guide · 21 reviews', location: 'Hayward', date: '6 years ago', rating: 5, body: 'One thing i have really enjoyed about coming to this office, is the first thing is they take really good care of me.  Health is vital to life and this office does not add to me extra unnessary test and medications. Being as healthy as i can …' },
  { name: 'Fe Williams', meta: '3 reviews', location: 'Hayward', date: '3 years ago', rating: 5, body: 'Don\'t let the humble building fool you. 5 star care inside. My 1st time going here and under less than idea circumstances being that I just got out of emergency hospital. The service from the nurses and from the doctor is beyond reproach. …' },
  { name: 'Bidur Khatri', meta: 'Local Guide · 36 reviews · 13 photos', location: 'Hayward', date: '5 years ago', rating: 5, body: 'I am regularly visiting Mission  Primary Care with Dr. Bhupender Bhandari for last 5 years. Dr Bhandari is very polite, caring, and excellent GI doctor. The supporting desk staffs are also nice but need to be more focussed on patients care.' },
  { name: 'jay ippolito', meta: '7 reviews · 1 photo', location: 'Hayward', date: '6 years ago', rating: 5, body: 'Mission primary care is fantastic...Dr.pareek is an awesome doctor, and cares about his patients and their well being...a few times my appointment was canceled and I never recieved a call stating so...so i drive all the way to his office …' },
  { name: 'Ronald Davis', meta: 'Local Guide · 30 reviews · 32 photos', location: 'Hayward', date: '5 years ago', rating: 5, body: 'HELLO. I’M A PATIENT OF DR. BHANDARI. I WENT IN TO THE FREMONT SURGERY CLINIC SEVERAL WEEKS AGO FOR A COLONOSCOPY. I WAS AFRAID. DR. BHANDARI AS WELL AS HIS SURGERY TEAM DID EVERYTHING NECESSARY TO MAKE ME COMFORTABLE AND RELAXED. THE …' },
  { name: 'Ramiro Canal', meta: 'Local Guide·14 reviews·1 photo', location: 'Fremont', date: '5 years ago', rating: 5, body: 'Doctors, nurses, front desk staff, everyone in Mission primary Care are polite and take a really good care of you,  everyone knows their jobs, no complaints from me at all :) actually, I would rate, giving them a great job, thumps  up.' },
  { name: 'Vikki Arellano', meta: '9 reviews · 2 photos', location: 'Hayward', date: '6 years ago', rating: 5, body: 'Doctor Bhandari has been my doctor for 27 years in my opinion he is outstanding and that\'s just a small word to use for him. I have also been seen by all the other nurse practitioners in this office and they are all just the same as …' },
  { name: 'Hyacinth Carcallas', meta: '5 reviews', location: 'Hayward', date: '5 years ago', rating: 5, body: 'Very easy to sign up for a Tele-Health appointment for Covid screening for my daughter online. Was able to book and appointment next day with many available times with several doctors. Now we can head to the Covid testing tomorrow.' },
  { name: 'Tarun Khanna', meta: '4 reviews', location: 'Fremont', date: '5 years ago', rating: 5, body: 'Dr. Bhandari is an extremely knowledgeable doctor. He has immense patience while dealing with his patients. He is encouraging and very supportive. The staff too is quite efficient. We are glad to have him as our physician.' },
  { name: 'Nina Ross', meta: '1 review', location: 'Hayward', date: '6 years ago', rating: 5, body: 'Mission Primary Care has a friendly and caring staff. I give them 10 stars. This is the best I’ve ever felt about a provider, I know they actually care. She immediately diagnosed my problem. My visit was very professional.' },
  { name: 'Gene Crawford', meta: '1 review', location: 'Hayward', date: '3 years ago', rating: 5, body: 'My husband and I have been going to Mission Primary care for close to 20 yrs and the staff & doctors have always been so good to us like family they are very understanding also fast referring us to outside help when needed' },
  { name: 'Brian OGuinn', meta: '8 reviews', location: 'Hayward', date: '6 years ago', rating: 5, body: 'I found that in these troubling moments the doctors and nurses assistant have lead the way to make my life a lot easier when it comes to seeing the doctor and setting up video conferencing call...nursing assistant...thanks' },
  { name: 'Yogendra Singh', meta: '10 reviews', location: 'Hayward', date: '4 years ago', rating: 5, body: 'Great service. Dr Bhandari does an excellent job in thoroughly diagnosing the problems and shares his analysis by suggesting different medications to tackle the problem. Highly recommended for primary physician needs.' },
  { name: 'Hemant Pradhan', meta: '2 reviews', location: 'Hayward', date: '6 years ago', rating: 5, body: 'Respected Dr. Bhandari, Dr.Khan & DR. Patwa,\nIt’s my pleasure to say thanks to all of you for taking our care in such a critical situation. Sir, we are members of our Mission Primary Clinic last 12 years. …' },
  { name: 'Angela Perez', meta: '2 reviews', location: 'Hayward', date: '6 years ago', rating: 5, body: 'My doctor is Dr Khan And this  has been a very hard time for me but my doctor has made it a  lot less stressful for me so I would like to thank him and his staff who  really care. About there patients' },
  { name: 'Paul Singh', meta: '2 reviews · 12 photos', location: 'Hayward', date: '6 years ago', rating: 5, body: 'It was quick response from Dr khan  Primary mission care Fremont  Ca  He is very humble with patients .Always listen patients problems carefully  God bless everyone at primary mission care be safe' },
  { name: 'Nilu Gupta', meta: '2 reviews', location: 'Fremont', date: '4 years ago', rating: 5, body: 'We are getting excellent services from our primary care Doctor. Dr. Bhupendar Bhandari and his staff of Mission Primary Care serving their patients with great care and devotion.\nProf..Nilu Gupta.' },
  { name: 'Safi Jan', meta: '1 review · 1 photo', location: 'Hayward', date: '5 years ago', rating: 5, body: 'The most amazing the most respectful dr and nurses in this beautiful hospital I mean there. Behave with patient is outstanding god bless them all to make happy life for community and country' },
  { name: 'Rashima Coleman', meta: '1 review', location: 'Hayward', date: '6 years ago', rating: 5, body: 'Everything was great I love the video appointment it’s convenient Audio was perfect video was clear and my dr was very compassionate as if I was in the office I give it a thumbs up' },
  { name: 'Rinku Peterson', meta: '2 reviews', location: 'Hayward', date: '6 years ago', rating: 5, body: 'Dr. Pareek is very professional and an experienced doctor.  He encourages to treat with lifestyle changes rather than just resorting to strong medications wherever possible.' },
  { name: 'G Pink', meta: '2 reviews', location: 'Fremont', date: '3 years ago', rating: 5, body: 'Doc B is and insightful and caring Dr.\nThe staff here are always helpful, kind and communicative and the systems they have in place make it a pleasure to be a part of.' },
  { name: 'C Garcia*', meta: '7 reviews', location: 'Fremont', date: '4 years ago', rating: 5, body: 'The staff was polite and helpful.. the office is in a good location.. Dr is patient and understanding the service was great I will definitely recommend him 👍🏽👌' },
  { name: 'MIRABDUL MOSHREF', meta: '1 review', location: 'Hayward', date: '3 years ago', rating: 5, body: 'Today I had an appointment with Dr. Bhandari. I had a great experience. Everything was perfect. Workers were very nice especially Dr. Bhandari.' },
  { name: 'Sumbul Beg', meta: '9 reviews', location: 'Hayward', date: '4 years ago', rating: 5, body: 'Very courteous staff. Dr.Bhandari really pays attention to his patients. He is very knowledgeable. The staff is responsive to all our needs.' },
  { name: 'Amandeep Gill', meta: '7 reviews', location: 'Hayward', date: '5 years ago', rating: 5, body: 'Dr. Bhandari and his staffs were great & professional. My mom dad is very happy with dr bhandari 🙏Thank you for your services. …' },
  { name: 'Boss Man', meta: '5 reviews', location: 'Hayward', date: '3 years ago', rating: 5, body: 'One of the best doctors and clinics in Fremont.\nDefinitely can’t complain.. dr Bhandari is amazing and appreciated!\nThank you …' },
  { name: 'Antonio Sanchez', meta: '1 review', location: 'Fremont', date: '6 years ago', rating: 5, body: 'My experience with dr Bhandari has been very\nInformative\nHelp full in regards to my situation\nThank you  for your care\nAntonio' },
  { name: 'Estella be', meta: 'Local Guide·60 reviews·30 photos', location: 'Fremont', date: '6 years ago', rating: 5, body: 'Great Clinic my Dr Bhandari listens to my issues and cares about each of his patients.  Have been going there for 5yrs.' },
  { name: 'Roy Lee', meta: '3 reviews', location: 'Hayward', date: 'Edited 6 years ago', rating: 5, body: 'I must say they are quick responsive To our needs an  Very helpful I\'m glad  To be a  Patient of you\'re facility🤝👍 …' },
  { name: 'Dominador Bumanlag', meta: '2 reviews·1 photo', location: 'Fremont', date: '3 years ago', rating: 5, body: 'Doctors are very accommodating as well as the staff. They address all questions regarding to my health problems.' },
  { name: 'Chris Puryear', meta: '5 reviews', location: 'Fremont', date: '3 years ago', rating: 5, body: 'The telemedical video call was hiģhly efficient and accomplished what we needed to arrange.  Very thankful.' },
  { name: 'Phyllis Jackson (PJ)', meta: 'Local Guide · 111 reviews · 468 photos', location: 'Hayward', date: '6 years ago', rating: 5, body: 'Dr. Khan is such a wonderful doctor. He cares about his patients well being. He is an excellent listener...' },
  { name: 'Poliana Lima', meta: '2 reviews', location: 'Fremont', date: 'Edited 3 years ago', rating: 5, body: 'I really enjoyed the service!  Dedicated and super polite people treated me very well, I highly recommend.' },
  { name: 'Masuod Afridi', meta: 'Local Guide · 35 reviews · 18 photos', location: 'Hayward', date: '6 years ago', rating: 5, body: 'I am certified from Dr. Gautam Pareek service, Spatially today I was with him in Virtual Exam Room (VER).' },
  { name: 'Adriana Rivera', meta: '4 reviews', location: 'Fremont', date: '3 years ago', rating: 5, body: 'Dr. Bhandari, was very caring and responsive when it came to my concerns. Great staff as well.' },
  { name: 'Jackie W', meta: '8 reviews · 1 photo', location: 'Hayward', date: '6 years ago', rating: 5, body: 'Dr. Bhandari and staff are wonderful people, I love the treatment I get on my appointment day.' },
  { name: 'Gursharan Singh', meta: '7 reviews', location: 'Hayward', date: '5 years ago', rating: 5, body: 'Dr Bhiandari is a great doctor he treats me like family he saved my life before and one again' },
  { name: 'Jennifer Holden High School', meta: '1 review', location: 'Hayward', date: '5 years ago', rating: 5, body: 'It could not have been simpler. Easy to set up an appointment and super quick to get tested.' },
  { name: 'Noor Sabah', meta: '1 review', location: 'Hayward', date: '6 years ago', rating: 5, body: 'Dr Bhndare office  has my good primary care and good Doctors and very good sarvis thank you' },
  { name: 'claudia munoz', meta: '4 reviews', location: 'Fremont', date: '6 years ago', rating: 5, body: 'Thanks for the help everyone at your clinic is very helpful, and I felt very welcome..' },
  { name: 'Ming', meta: '4 reviews', location: 'Hayward', date: '6 years ago', rating: 5, body: 'Dr. Bhandari and his staffs were great & professional. Thank you for your services.' },
  { name: 'Cherri Logan', meta: '10 reviews', location: 'Fremont', date: '3 years ago', rating: 5, body: 'Dr. Khan has been my Dr for many years. The best physician I\'ve ever had!' },
  { name: 'NaToya Lee', meta: '5 reviews·1 photo', location: 'Fremont', date: '6 years ago', rating: 5, body: 'Great service. Really professional and I was out in 20 minutes today....' },
  { name: 'Nirmal Mudhar', meta: '1 review', location: 'Fremont', date: '5 years ago', rating: 5, body: 'Had a good experience in the office.  Staff is very friendly.' },
]
